
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #如果用的云上托管版本，输入可访问的Nacos Server地址即可
    gateway:
      routes:
        - id: alibaba-server-payment
          uri: lb://cloud-alibaba-payment
          predicates:
            - Path=/alibaba/**

  #      serverAddr: 127.0.0.1:8848 #如果用的云上托管版本，输入可访问的Nacos Server地址即可
  config:
    import: # 这里nacos:xxxxxx.properties指的是具体的nacos需要加载的配置文件
      - nacos:nacos-config-example.properties?refreshEnabled=true
  application:
    name: cloud-alibaba-gateway9527
server:
  port: 9627
