server:
  port: 8001

# ==========applicationName + druid-mysql8 driver===================
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  profiles:
    active: dev # 多环境配置加载内容dev/prod,不写就是默认的default
  jackson:
    date-format: yyyy-MM-dd hh:ss:mm
    time-zone: GMT+8

# ========================mybatis===================
mybatis-plus:
  mapper-locations: "classpath:mapper/*.xml" #Mapper.Xml文件地址
  configuration:
    map-underscore-to-camel-case: true #是否开启下划线和驼峰的映射
    cache-enabled: false #是否开启二级缓存
  global-config:
    db-config:
      id-type: assign_id #id为雪花算法生成
      update-strategy: not_null #设置更新策略：只更新非空字段


# ==========================zipkin配置==========================
management:
  zipkin:
    tracing:
      endpoint: http://127.0.0.1:9411/api/spans # 固定默认的zipkin访问地址
      connect-timeout: 1s # 访问超时连接时间默认为1s
  tracing:
    sampling:
      probability: 1.0 # 采样率 默认为0.1(这个其实就是10次中只有1次被采样收集下来，值越大采集的效果就越好)

test:
  info: hhhhhh