server:
  port: 9527

spring:
  cloud:
    consul:
      port: 8500
      host: 127.0.0.1
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: pay_rout1 # 路由的ID 类似于mysql中的主键，没有固定要求但是要求唯一性
#          uri: http://127.0.0.1:8001  # 匹配后提供服务的路由地址(直接写死，不会进行负载均衡)
          uri: lb://cloud-payment-service # 使用lb+微服务名称实现动态绑定微服务访问地址
          predicates:
            - Path=/pay/gateway/** # 断言，路径相匹配则进行路由，否则不进行路由
#            - After=2025-08-11T23:11:21.073955800+08:00[Asia/Shanghai]
#            - Before=2025-08-11T23:14:21.073955800+08:00[Asia/Shanghai]
#            - My=diamond
          filters:
            - AddRequestHeader=X-Request-color, blue #在请求  http://127.0.0.1:8001服务时，会给该请求头自动添加上 X-Request-
            - My=token,open
        - id: pay_route2
#          uri:
#            http://127.0.0.1:8001
          uri: lb://cloud-payment-service # 使用lb+微服务名称实现动态绑定微服务访问地址
          predicates:
#            - My=diamond
            - name: My
              args:
                userType: diamond
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false

  #            - Path=/pay/gateway/info/**
#            - After=2025-08-11T23:09:21.073955800+08:00[Asia/Shanghai]

  application:
    name: cloud-gateway9527

# 服务名字使用 - 连接并且不能使用数字开头!!! 巨坑


